title: Shakiv Hussain # your name (or website title) here
logo: "/profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 Android Developer
  <br><br>
  <a href="mailto:shakibraza436@gmail.com@gmail.com">shakibraza436@gmail.com </a>
  <br>
  <a href="https://www.linkedin.com/in/shakib-hussain/">LinkedIn Profile</a>
  <br>
  <a href="https://www.gihub.com/shakivhussain/">Gihub</a> 
theme: jekyll-theme-minimal
